### PR TITLE
fix(chips): Final Design QA

### PR DESCRIPTION
**Pull request by matttelliott-flosports**
New link:
https://flo-scss-finish-chips-brcr5vk6.herokuapp.com/docs/components/chips/

### CODE REVIEW

**Comment by bexux** [comment]
Chips with Badges - For the Close icon:
- On the hover state, we need to keep the text color and background color the same (bg is grey-300). No border color. Only the circle around the "x" has a color change. Light color (non-hover) is grey-500, and hover is grey-600. 
- Can remove linear-gradient on hover

**Comment by bexux** [comment]
Chips with Badges: And we can remove Watch "Live" and Event "Flosports" examples from the docs because it could be confusing.

**Comment by bexux** [comment]
For all of the chips under examples, we need to remove the gradients on those. Just keep the first color and keep it flat.
(Primary, Secondary, Success) etc.

**Comment by ArianneArcher** [comment]
[chips](https://user-images.githubusercontent.com/31702746/76121259-37570c80-5fc1-11ea-8e69-ce5d5789b41c.png)

Need to add combined components that make up our brand chip 

chip grey-300
with close icon 
!

**Comment by ArianneArcher** [comment]
Need to add combined components to display the flobrand chip. Ref Zeplin

Change request and detailed notes added to Jira as well. 
:https://flocasts.atlassian.net/browse/FLO-11032

**Active state**
bg-color: $gray-300;
text-color: $gray-600;
padding-right after icon should = 8px;

**Hover state**
change icon-close-circle bg-color: $gray-600


chips

On further inspection additional changes are need to the button chip. Here are the additional CSS changes made with inspector to be inline with the style guide

- padding-left:24px;
- padding-right:34px;
- :after
  - height:18px;
  - right:8px;

**Comment by ArianneArcher** [comment]
##### TODO 
 * Update chips radius from 17px to 16px
 * Update chip text color to $gray-600 
* Fix sizing issues height should be 32px
** Chrome renders 30.07px
** Firefox renders 31.2px
** Safari renders 30px 

* Update documentation separating what is part of the FloSports brand from what System Extras are inherited from forking Bootstrap 4
** Here is the updated markdown with TODO notes. 
[chips.md.zip](https://github.com/flocasts/flo-scss/files/4364013/chips.md.zip)


-----

_PLEASE NOTE: review is based on running updated local.  [Link](https://flo-scss-finish-chips-r7hl20np.herokuapp.com/docs/components/chips/) on pull request goes to a No such app link _

Chips-review-link

**Review by bexux — APPROVED** [review]

**Pull request merged**
