### PR TITLE
fix(tabs): Final Design QA

### PR DESCRIPTION
**Pull request by matttelliott-flosports**
https://flo-scss-finish-tabs-euuaorm10.herokuapp.com/docs/components/tabs/

### CODE REVIEW

**Comment by bexux** [comment]
For the documentation - each tab should show an example of different content type.
One with a header, one without, one with an image as an example.

Note - the EA designs are showing tabs with a set width. This is not the pattern we will be using. We will be using this pattern here.

**Comment by ArianneArcher** [comment]
Tabs need to display full equal widths, bottom red line spans width of container not just the text.


Screen Shot 2020-03-06 at 2 14 49 PM

**Review by bexux — APPROVED** [review]
awesome awesome awesome

**Pull request merged**
