### PR TITLE
fix: navbar spacing issues

### PR DESCRIPTION
**Pull request by bexux**
LINK: https://flo-scss-flo-11185-clea-lurr98.herokuapp.com

Bootstrap has some scss files specifically for it's documentation page. We were missing one for the navbar so I added it back in. I renamed the `bd-navbar` class to `flo-doc-navbar` to be explicit that it is for the documentation page.

SVG Icons are fixed in FF and I removed all icons except GitHub.

Screen Shot 2020-03-24 at 10 09 59 AM

Additionally the flogo.svg needed jekyll imports for the classes to be applied to it.
```
{% if include.class %} class="{{ include.class }}"{% endif %}
```

### CODE REVIEW

**Comment by ArianneArcher** [comment]
**Good news**
Not seeing the crazy size shift previously seen in firefox


**Odd News**
Noticing the logo is running into/overlapping the first navbar link and the download button on the right, looks like the padding-right is missing from .navbar
navbar-sans-padding

**Comment by bexux** [comment]
@ArianneArcher  that issue has been fixed.

**Comment by ArianneArcher** [comment]
Looks good

**Review by Chrisitchy — APPROVED** [review]

**Pull request merged**
